name: nodeJS CI
on: push

jobs:
  frontend:
    runs-on: ubuntu-latest
    env:
        working-directory: ./frontend
    steps:
    
    
    - uses: actions/checkout@master
    - name: working directory
      run: ls -R
      working-directory: ${{env.working-directory}}
    - name: directory frontend
      run: |
         npm i
         #npm run test
         npm run build

      working-directory: ${{env.working-directory}}
      
  
  build:
      name: Test app

      runs-on: ubuntu-latest

      steps:
        - name: Checkout repo
          uses: actions/checkout@v2

        - name: Download Deno
          uses: denolib/setup-deno@master
          with:
            deno-version: v1.1.2

        - name: Check format
          run: deno fmt --check

        - name: Run tests
          run: deno test --allow-read --allow-write
 
 
 
