name: nodeJS CI
on: push

jobs:
  frontend:
    runs-on: ubuntu-latest
    env:
        working-directory: ./frontend
    steps:
    
    
    - uses: actions/checkout@master
    - name: working directory
      run: ls -R
      working-directory: ${{env.working-directory}}
    - name: directory frontend
      run: |
         npm i
         #npm run test
         npm run build

      working-directory: ${{env.working-directory}}
      
  backend:
    runs-on: ubuntu-latest
    env:
        working-directory: ./backend/src
    steps:
    
    
    - uses: actions/checkout@master
    - name: working directory
      run: ls -R
      working-directory: ${{env.working-directory}}
    - name: directory frontend
      run: |
         curl -fsSL https://deno.land/x/install/install.sh | sh
         deno run --allow-all main.ts
       
       

      working-directory: ${{env.working-directory}}
    
      
