name: nodeJS CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        working-directory: ./frontend
    steps:
    
    
    - uses: actions/checkout@master
    - name: working directory
      run: ls -R
      working-directory: ${{env.working-directory}}
    - name: directory frontend
      run: |
         ls -R
      working-directory: ${{env.working-directory}}
    
      
