name: nodeJS CI
on: push

jobs:
  frontend:
    runs-on: ubuntu-latest
    env:
        working-directory: ./frontend
    steps:
    
    
    - uses: actions/checkout@master
    - name: working directory
      run: ls -R
      working-directory: ${{env.working-directory}}
    - name: directory frontend
      run: |
         npm i
         #npm run test
         npm run build

      working-directory: ${{env.working-directory}}
      
  
  test:
      runs-on: ubuntu-latest

      steps:
        - name: Set up repo
          uses: actions/checkout@v2

        - name: Set up Deno
          uses: denolib/setup-deno@v2
          with:
            deno-version: v1.x

        - name: Cache Dependencies
          run: deno cache deps.ts

        - name: Run Tests
          run: deno test -A --unstable
 
 
 
